"""Añadir biografia y foto a Medico

Revision ID: 74f84ad34a8b
Revises: 5b8b5004c820
Create Date: 2025-10-19 10:22:59.853451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f84ad34a8b'
down_revision = '5b8b5004c820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biografia', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medico', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('biografia')

    # ### end Alembic commands ###
